### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sidxz**
Make it obvious that user creation will be skipped if the user's groups do not include the user_manage module's group name.

# Description

Updated Read me for a better description of user_manage module behavior.

## Issues Resolved

None
Edit to ReadMe only

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [Y] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by Stromweld** [comment]
can you please fix the MDL linting errors.

**Comment by sidxz** [comment]
MDL errors are fixed

**Review by Stromweld — APPROVED** [review]
looks good

**Review by Stromweld — APPROVED** [review]
LGTM

**Comment by Stromweld** [comment]
I piggy backed on this PR to update the CI pipeline

**Comment by kitchen-porter** [comment]
Released as: [8.1.3](https://github.com/sous-chefs/users/releases/tag/8.1.3)

**Pull request merged**
