### PR TITLE
Set a default for users property

### LINKED ISSUE #450: Allows `users` to be unset.
## :person_frowning: Problem Statement

We've been creating groups like this:
```ruby
  grp = data_bag_item('groups', name)

  users_manage grp['id'] do
    group_id grp['gid']
    action :create
```

This gets compiled to something like this (slightly redacted):

```ruby
    users_manage("…") do
      action [:create]
      default_guard_interpreter :default
      declared_type :users_manage
      cookbook_name "…-users"
      recipe_name "production"
      group_id …
      group_name "…"
    end
```

This worked until 6.0.0. From 6.0.0, we're getting an error like this:

```
FATAL: NoMethodError: users_manage[…] (…) had an error: NoMethodError: undefined method `each' for nil:NilClass
```

It's easy to see why this happens: https://github.com/sous-chefs/users/blob/6.0.0/resources/manage.rb#L34

This is the line pointed to by a stack-trace (not included).

## :grey_question: Possible Solution

It'd be quite nice if `users` was set to be empty collection if it is not defined. This would allow definitions like ours to keep working transparently.

## :arrow_heading_up: Describe alternatives you've considered

We can set the cookbook version bound to `< 6.0.0` or specify users to be an empty collection.

## :heavy_plus_sign: Additional context

Not really a bug as we're jumping a major version but it seems low effort to make it Just Work™, hence a feature request.

### PR DESCRIPTION
**Pull request by Fuuzetsu**
I fix a typo on the same line while there.

Fixes #450

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Review by frank-m — DISMISSED** [review]
LGTM, please merge the changes when convenient.

If you add a line to the changelog under unreleased that would be nice for clarity :)

**Review by ramereth — CHANGES_REQUESTED** [review]
Please add an entry to the changelog.

**Comment by Fuuzetsu** [comment]
I've added a CHANGELOG entry.

**Comment by Fuuzetsu** [comment]
> Will this actually create the group?
> 
> https://github.com/sous-chefs/users/blob/master/resources/manage.rb#L53-L61, where the group is created, is within the users loop so it won't be run with an empty array. Please correct me if I am wrong!
> 
> I think that group block needs to be brought out of the users loop

I think you're absolutely right: I just kind of assumed it worked: the test has to be improved and the group creation should just be checked for and created once, irrespective of users. I'll see what I can do on Monday.

**Comment by Fuuzetsu** [comment]
It took a few tries but I manage to pull out the group code out of the users loop and I added a test that verifies that the group is actually created and does not have any members in it. PTAL.

**Comment by ramereth** [comment]
@Fuuzetsu looks like we need to fix the InSpec on MacOS. I have a commit which will fix it but maintainers don't have access on this PR to push to the branch. Can you please allow maintainers access so I can do that?

**Comment by Fuuzetsu** [comment]
> I have a commit which will fix it but maintainers don't have access on this PR to push to the branch. Can you please allow maintainers access so I can do that?

It appears this can only be done if the fork is on a user account while the branch is on organisation account ;/

If you post the patch somewhere, I can put it into the branch. Or you can take this commit, apply the patch, push it in and just close the PR, I don't mind either way.

**Comment by ramereth** [comment]
@Fuuzetsu you can cherry-pick this commit https://github.com/sous-chefs/users/commit/3290af8588c1cf83bc6b61637850e60bebcddad2

**Comment by Fuuzetsu** [comment]
> @Fuuzetsu you can cherry-pick this commit [3290af8](https://github.com/sous-chefs/users/commit/3290af8588c1cf83bc6b61637850e60bebcddad2)

Done, CI seems to pass.

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [6.0.2](https://github.com/sous-chefs/users/releases/tag/6.0.2)

**Pull request merged**
